### ISSUE TITLE
Dense Matrix multiplication

### ISSUE THREAD

**Issue by lazywei** [gonum/matrix#104]
Hi,

When I tried to multiply one matrix to another one,

```
	camMat.Mul(camMat, stackedMat)
```

(both are dense matrix), it complains:

```
cannot use stackedMat (type mat64.Dense) as type mat64.Matrix in argument to camMat.Mul:
	mat64.Dense does not implement mat64.Matrix (At method has pointer receiver)
```

I'm not sure why ... what is the correct way to do matrix multiplication then?

**Comment by btracey** [comment]
The complier message says it -- "At method has pointer reciever". The type Dense does not implement matrix, a *Dense does. stackedMat needs to be a pointer to Dense, or you need to use
camMat.Mul(camMat, &stackedMat)

In the future, please ask questions on the gonum-dev mailing list.
