### ISSUE TITLE
go test produces error on OSX10.9 -framework Acellerate: Idamax NaN & NaNInc  

### ISSUE THREAD

**Issue by AndreasBriese** [gonum/matrix#109]
$ go test
--- FAIL: TestIdamax (0.00 seconds)
	level1double.go:1155: idamax: mismatch NaN: expected 0, found 1
	level1double.go:1155: idamax: mismatch NaNInc: expected 0, found 1
FAIL
exit status 1
FAIL	github.com/gonum/blas/cgo	0.063s

Environment:
Mac OSX10.9 CGO_LDFLAGS="-framework Accelerate"

Behaviour:
commenting out the test (or altering the expected value to 1) produces NO errors

Comment:
see nothing going wrong in the implementation: might be an error in Apples framework. Maybe should be announced to user at test time and maybe should be handled by an if clause on darvin?

**Comment by jonlawlor** [comment]
As you say, there is some disagreement between various frameworks.  I don't think there is agreement yet on how to handle it.  Before eliding tests like this, we have to determine how to make the library present a consistent interface.

**Comment by AndreasBriese** [comment]
I digged a little deeper - the Test expectance (expected return value index 0) for the test idamax with [NaN, 2] incr 1 and [NaN, NaN, 2] incr 2 might be wrong. Should be 1 (index 1) in both cases, shouldn't it.  
If so, blas/testblas/level1double.go line 330 and line 350 should state 

		Idamax: 1,

**Comment by btracey** [comment]
As has been pointed out, NaN is tricky, and there is disagreement. OpenBLAS, for example, passes the test suite. If it is coded in the obvious way (as it is in blas/native)
````
for i, v := range x {
    absV := math.Abs(v)
    if absV > max {
        max = absV
    idx = i
    }
}
````
you get the answers that are in the test suite.

It's not clear how to fix it. It's not true that we want to trigger special things on Darwin, because it's a property of the accelerate framework and not a property of the operating system. Using OpenBLAS on Darwin does not produce any errors.

**Comment by kortschak** [comment]
It's a pity BLAS implementations don't agree on this, but I don't think it is our job to either fix this or ensure that all BLAS implementations work with our front end. We do say which BLAS we recommend, perhaps in gonum/blas we should make it more clear that we test against OpenBLAS with blas/cgo and therefore other disagreeing implementations may fail tests.

**Comment by kortschak** [comment]
BTW This should be against gonum/blas not gonum/matrix. Moving there as a documentation issue.

As an aside - both the OpenBLAS and Accelerate behaviours are arguably incorrect. IMO the presence of a NaN should result in the return of -1.
