### ISSUE TITLE
mat64: documentation is lacking

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#112]
This is a post hoc issue to cover the work in #105.

**Comment by btracey** [comment]
Was this closed with #113? Documentation could always use improving, but it's better to have issues with concrete meaning.

**Comment by kortschak** [comment]
Probably. We might want to add more examples, but that can be a separate issue.

**Comment by btracey** [comment]
Yea, we can also have a "friendlier" doc comment that doesn't look like a giant block of text.
