### ISSUE TITLE
mat64: Feature request for variadic matrix multiplication

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#121]
This is a feature request for 
````
func (m *Dense) MulBatch(a ...Matrix)
````
The computation time for matrix multiplication can be significantly faster depending on the ordering. For example, multiplying
````
(n, 1) x (1, n) x (n, n)
````
It's much faster to do the (1,n) x (n,n) first, and then multiply the final two vectors, then to do the vector multiplication and then multiply the two (n,n) matrices. This problem can be solved through dynamic programming. In gonum, we can do even better than this because of the Matrix interface. We can use reflection to see the underlying Matrix type (SymDense/BandPacked/etc.) and use the order of operations counts from the multiplication. This allows automatic efficient multiplication order of arbitrary types (pretty neat)

We probably want the function signature to pair a matrix type with a "transpose", as complicated matrix multiply expressions almost always have them.

**Comment by kortschak** [comment]
This and the offline conversation that preceded it has suggested to me an API change that simplifies the Mul and MulTrans into a single method.

In short we add a `Transpose struct { Matrix }` with a Dims and At method that transposes the embedded matrix. In itself, this is not wildly useful, but it can be used internally to signal the transpose state to the Mul routine. This allows us to retire the MulTrans API, keeping its optimisations (we could keep it, but this is worth thinking about).

Identifying the transpose state would be done by a helper that walks the T chain until the underlying Dense (or other optimisable type) is found, keeping track of the state. Additionally, I think a helper T(Matrix) Matrix would be worthwhile to optimise this process:

func T(m Matrix) Matrix {
    if t, ok := m.(Transpose); ok {
        return t.Matrix
    }
    return Transpose{m}
}

**Comment by kortschak** [comment]
(Apologies for hijacking) The above T proposal is complicated by Dot which does not match our receiver-is-assigned-to convention. Transpose{*Dense}.Dot(Matrix) is not properly resolvable without adding Dot to Transpose. Dot should probably change.

I'll file and issue for the proposal above.
