### ISSUE TITLE
mat64: consider retiring less used interface definitions

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#138]
The interface definitions in matrix.go served a useful purpose in defining the direction of development for mat64. We now have a fairly well defined set of interfaces based on the concrete types, so with the exception of interfaces that are used within the package or are likely to be useful to clients we should start considering retirement for these.

Please add you thoughts on which should be retired and which should stay.

**Comment by kortschak** [comment]
My proposed list of interfaces to delete based on a quick glance:

 - [ ] Matrix
 - [ ] Mutable
 - [ ] Vectorer
 - [ ] VectorSetter
 - [ ] RowViewer
 - [ ] RawRowViewer
 - [ ] ColViewer
 - [ ] RawColViewer
 - [ ] Cloner
 - [ ] Reseter
 - [ ] Copier
 - [ ] Viewer
 - [ ] Grower
 - [x] Normer
 - [x] TransposeCopier
 - [x] Transposer
 - [x] Deter
 - [x] Inver
 - [ ] Adder
 - [ ] Suber
 - [ ] ElemMuler
 - [ ] ElemDiver
 - [ ] Equaler
 - [ ] ApproxEqualer
 - [ ] Scaler
 - [ ] Sumer
 - [ ] Muler
 - [ ] MulTranser
 - [x] Exper
 - [x] Power
 - [ ] Dotter
 - [x] Stacker
 - [x] Augmenter
 - [x] Applyer
 - [x] Tracer
 - [x] Uer
 - [x] Ler
 - [ ] BandWidther
 - [ ] RawMatrixSetter
 - [ ] RawMatrixer
 - [ ] RawVectorer
 - [ ] Symmetric
 - [ ] RawSymmetricer
 - [ ] Triangular
 - [ ] RawTriangular

Collaborators feel free to edit this post to add or delete check marks (please note if you make a change what the change was).

**Comment by btracey** [comment]
Equaler and Deter are gone.
