### ISSUE TITLE
Deter interface but Det function

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#159]
There is a conceptual inconsistency in mat64 with determinants. There is a Deter interface, and some of the types have a Det function (LUFactors for example). There is also a Det function which finds the determinant of an arbitrary matrix. This seems to violate "only one way to do it". Should we instead provide Det() methods on Dense and Triangular (for example)?

**Comment by kortschak** [comment]
Unless there are significant efficiencies to gain I don't think so. So probably we should drop Deter.

**Comment by btracey** [comment]
There are significant efficiencies to gain. For example a Triangular determinant is the product of the diagonal elements. This could also be type-switched in the Det function, though perhaps that is worse than providing methods.

**Comment by kortschak** [comment]
In that case optionally return the result of m.Det() mat64.Det when m is a Deter - and add Det where it is beneficial.

**Comment by btracey** [comment]
This was fixed with This was fixed with #209
