### ISSUE TITLE
Decide on Pool behavior for non-*Dense types

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#160]
The matrix pools we have now store *Dense. Instead, they should store []float64 so the pools can be shared between different matrix types.

**Comment by btracey** [comment]
Related, should NewDense (and NewX by extension) attempt to grab from the pools instead of automatically allocating?

**Comment by btracey** [comment]
Alternately we could have different pools for the different matrix types. The complicated code is bits, which will be shared among all pools.

**Comment by kortschak** [comment]
New should not pull from a pool. I would prefer different pools for different types - otherwise we allocate the container. Size is an issue, but so is the total number of allocations.

**Comment by btracey** [comment]
Could you explain why it shouldn't pull from a pool? I understand that it's different, but I don't see the harm.

**Comment by kortschak** [comment]
When you make a []float64 for a matrix, you can tune the size to exactly the length that you need and the default behaviour of New when given a nil []float64 is to do exactly that. Drawing from the pool only guarantees that the slice will be <2x the needed length. For temporary use, this is not an issue, but when people call New, they are presumably wanting to keep the data for a while. The upshot of this is that in the easy use case (which we all tend to use - passing nil) we potentially almost double memory usage (on average it would be 1.5x).

**Comment by btracey** [comment]
Thanks.

**Comment by kortschak** [comment]
I think this can be closed; the decision is made and at least one implementation reflecting the decision has been put in place.
