### ISSUE TITLE
SymDense copy Panicks on zero valued matrix

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#171]
Right now, the following code panics with "blas64.Symmetric not upper".
````
s := &mat64.SymDense{}
var s2 mat64.SymDense
s2.Copy(s)
````
The panic is that s has 0 for the blas.Uplo field, and not blas.Upper (or blas.Lower for that matter). 

I assume this should not panic and we should only check for invariants when the size is not zero. Assuming that is the correct behavior, we should probably update testTwoInput to give the real zero value for zero size. Wouldn't catch this bug, but the future testOneInput would catch this.

**Comment by kortschak** [comment]
I'm not 100% sure what the behaviour should be, but if it does panic the panic should be more informative and more consistent (all zero matrices should panic if one does). Including a zero matrix as an input parameter is probably classable as a programmer error, but these will be caught by arithmetic operations with no significant extra cost or debugging effort when found.

These two things suggest that we should probably pass early and allow the failure to be detected later - it's easier and not significantly more costly in operation or debugging for clients.

On a side note, in the matrix type test matrix in testTwoInput, many of the types are defined by the return from a New function. Should we include the pure zero value (either in addition or as a replacement)?

**Comment by btracey** [comment]
Most of these will be caught by arithmetic operators. This came up in a machine learning algorithm where data comes in a stream. When necessary, I append to an existing matrix. At the start, there is no data, so the existing data has zero size. 

> On a side note, in the matrix type test matrix in testTwoInput, many of the types are defined by the return from a New function. Should we include the pure zero value (either in addition or as a replacement)?
Yes, I think so, that's what "Assuming that is the correct behavior, we should probably update testTwoInput to give the real zero value for zero size." was intending to say. I guess the correct way to do this is to have a special zero loop where we test zero values of various sizes to make sure things are okay?
