### ISSUE TITLE
Request: condense Formatted output

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#189]
For one of my matrices, this is the Formatted output:

````
a =
⎡                   0                     0   0.44669228806208794                     0                     0                     0⎤
⎣                   0  -0.23053805434391994   -0.8084250657828511                     0                     0                     0⎦
````
The spacing of each column is the same, even though only two of the columns are that wide. It would be nice if the columns that are all zeros were compressed.

**Comment by soniakeys** [comment]
Hmm, I'm not sure I would always want that.  I can see it would be nice in some cases, but I might often be happy with something more like `fmt.Printf("a = % .3f\n", mat64.Formatted(m, mat64.Prefix("    "), mat64.DotByte('0')))` giving

````
a = ⎡     0       0   0.447       0       0       0⎤
    ⎣     0  -0.231  -0.808       0       0       0⎦
````

**Comment by kortschak** [comment]
Do you need that level of precision? I don't think MATLAB/octave, R or python do this kind of formatting.

If it's really important we can do it; either we need to keep individual column width stats (there's a reasonably elegant way to do this without code duplication in the maxCellWidth function) or we can send the rows to tabwriter. What is the preferred method of indicating that compression should done, option or flag (I'm thinking option).

**Comment by btracey** [comment]
It's not "really important" necessarily. As far as I know, the main use of Formated is to help print to the screen. If that is the use case, I would think the best thing is to compress horizontally where possible to allow the most elements on a single line.

**Comment by kortschak** [comment]
Where possible and asked for though. Are you OK with adding a Squeeze option function, off by default.

**Comment by kortschak** [comment]
The other question is are you wanting to compress columns that are zero, or compress columns to their narrowest possible, or both configurably.

**Comment by btracey** [comment]
My ideal world would be that it compresses columns to their narrowest possible by default. For my use cases, it seems like that's what I would always want.

**Comment by kortschak** [comment]
This is not my preferred option. The reason for this is that spatial arrangement aids in pattern recognition; without explicit column identifiers this becomes important for easily identifying column identities. This is backed up by a quick survey of behaviours: R squeezes but provides identifiers, numpy and octave have uniform width and no identifiers.

I'd argue that the purpose of Formatted is not to print a matrix to the screen, but to aid a human's interpretation of that matrix, printing is merely a mechanism to that end. With that and the previous paragraph in mind, I prefer to have regularly spaced columns. Obviously, this reflects a personal bias - I am a visual thinker.

If space is an issue it seems to me that giving a smaller prec verb modifier gets pretty much exactly what you want, room to display what you have on the screen - hence my question above of whether you need the precision that is being displayed there.

```
package main

import (
	"fmt"

	"github.com/gonum/matrix/mat64"
)

func main() {
	a := mat64.NewDense(2, 6, []float64{
		0, 0, 0.44669228806208794, 0, 0, 0,
		0, -0.23053805434391994, -0.8084250657828511, 0, 0, 0,
	})

	// I'd prefer "% .2v" here since it draws the eye better.
	fmt.Printf("a =\n%.2v\n", mat64.Formatted(a))
}
```
```
$ go run Desktop/fmtmat.go 
a =
⎡    0      0   0.45      0      0      0⎤
⎣    0  -0.23  -0.81      0      0      0⎦
```

**Comment by btracey** [comment]
Yea, I can do that. The specific case is hard because I was trying to find a problem that turned out to deal with floating point error, which is not a typical case. Just a suggestion.

**Comment by kortschak** [comment]
Is this OK?

```
package main

import (
	"fmt"

	"github.com/gonum/matrix/mat64"
)

func main() {
	a := mat64.NewDense(2, 6, []float64{
		0, 0, 0.44669228806208794, 0, 0, 0,
		0, -0.23053805434391994, -0.8084250657828511, 0, 0, 0,
	})

	fmt.Printf("a =\n% v\n", mat64.Formatted(a, mat64.Squeeze()))
}
```
```
$ go run fmtmat.go 
a =
⎡.                     .  0.44669228806208794  .  .  .⎤
⎣.  -0.23053805434391994  -0.8084250657828511  .  .  .⎦
```
