### ISSUE TITLE
Create example for Cholesky factorization

### ISSUE THREAD

**Issue by ericdfournier** [gonum/matrix#215]
The updated routines for handling Cholesky decomposition -- which are now based upon the passing of a *Cholesky struct -- do not seem to contain a function for initializing those structures.

Perhaps a 'NewCholesky()' function, or something of the like, which takes as input arguments 'DenseTri' inputs could be added to facilitate this process.

Thanks to all of the contributors for your hard work in making this project great. 

- Eric Fournier

**Comment by btracey** [comment]
The short answer us you can say

var chol Cholesky
chol.Factorize(A)

**Comment by ericdfournier** [comment]
Thanks!

**Comment by btracey** [comment]
Reopening this to remind us to create an Example.

**Comment by kortschak** [comment]
Closed by #216.
