### ISSUE TITLE
Redesign SVD

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#244]
SVD should be like the other factorizations, struct type with a factorize function. The open question is arguments. Can we get away with zero values as a reasonable default?

For future reference, it seems like the appropriate lapack routine is Dgesdd (https://groups.google.com/forum/#!topic/julia-dev/mmgO65i6-fA)

**Comment by btracey** [comment]
By arguments I meant the inputs that are there now, WantU, WantV, and Tol. However, looking at Dgesdd it seems like there is only one enum input, so it's easy to use as a zero value.

**Comment by kortschak** [comment]
OK. I think we can throw out the whole current API. It seems like it could just be SVD.Factorize(Matrix, bool) where the bool translates to true:A, false:N. Alternatively just always do A.
