### ISSUE TITLE
mat64: SymDense has paths coded that are not reachable

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#261]
We don't support lower symmetric matrices via mat64, though we do via blas. However there are paths in Max, Min that cannot be reached because they examing the lower triangle of the data slice.

In itself this is not a problem, but that code cannot easily be tested (list_test tests won't allow it because they depend on CopySym which will panic when handed a lower-encoded symmetric matrix) and I don't see any real reason to keep it if there is no easy way to create a SymDense in this state.

When SetRawSymmetric is added it should panic if the blas64.Symmetric is lower (a similar check for blas.Unit should be done for SetRawTriangular when it appears).

**Comment by btracey** [comment]
Oops, sorry for adding those paths. Agreed on SetRawSymmetric.

**Comment by kortschak** [comment]
BTW There are similar paths in triangular.go in copySymIntoTriangle but we don't do list_tests on Cholesky that calls that and I don't know what the longer term plans are there. Also getBlasTriangular is not called at all.
