### ISSUE TITLE
Cond with 1 or inf norm returns 1 for a matrix of all zeros

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#273]
````
package main

import (
	"fmt"
	"math"

	"github.com/gonum/matrix/mat64"
)

func main() {
	a := mat64.NewDense(1, 1, nil)
	fmt.Println(mat64.Cond(a, 1))
	fmt.Println(mat64.Cond(a, 2))
	fmt.Println(mat64.Cond(a, math.Inf(1)))
}
````

This may be a bizarre quirk of the lapack function, but this should not be the final output from mat64.

**Comment by kortschak** [comment]
Should `Cond(zero, 2)` be NaN or Inf? I can see arguments both ways, though I lean towards NaN.

**Comment by kortschak** [comment]
There is a trivial fix and I believe this is a bug in LAPACK. DGECON returns early if anorm == 1 and [so does the native Gecon](https://github.com/gonum/lapack/blob/master/native/dgecon.go#L36) as we would expect given the provenance. If this early exit is removed, +Inf is returned. Presumably we should be returning `math.Inf(1)` here instead.

**Comment by kortschak** [comment]
Also note that native Trcon returns 1 for n=0 where Gecon returns 0. Presumably these should agree.

**Comment by kortschak** [comment]
Whooops.

I was just about to file an issue with NETLIB and no. The issue is a transcription error, one that explains the difference between Gecon and Trcon. The PR above will now reflect that discovery.

**Comment by btracey** [comment]
Ah, sorry. 

I would think that it should return Inf. It's very convenient to have comparisons work correctly (with a specific condition number), and I don't see any usefulness in NaN relative to Inf.

**Comment by kortschak** [comment]
No worries. It presumably will return Inf when SVD is fixed to use lapack routines. I think the LAPACK behaviour for zero sized matrices is wrong, but we don't see that in mat64 because we panic anyway.
