### ISSUE TITLE
matrix/{,cmat128}: add package documentation

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#282]
See https://github.com/gonum/matrix/pull/281#issuecomment-150608626 and https://github.com/gonum/matrix/pull/281#issuecomment-150679516.

The idea of doing text munging does not appeal (we already do too much of this elsewhere and I don't want to add to that). I propose we write a matrix/gendoc.go (with `//+build ignore`) that holds the canonical package documentation for each of matrix, mat64 and cmat128 as a text template and have it emit doc.go for each of the three packages. Along with this we should add a go generate test for travis the same is exists in gonum/blas.

To start this we need to sort out what are common sections and what are package specific.

\cc @btracey

**Comment by btracey** [comment]
SGTM. I would recommend we flesh out cmat a little more before we answer this (for example, deciding on #284 )

**Comment by kortschak** [comment]
This is not really massively impacted by #284.

**Comment by btracey** [comment]
No, but how much is package specific is. Agreed that we should start thinking about it.
