### ISSUE TITLE
cmat128: Matrix should have a conjugate transpose

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#283]
`H` or `Conj`?

**Comment by btracey** [comment]
I think it should be H(). It's concise, matches T(), and the notation is very common.

In terms of having T(), H() or H() and T(), if one looks at http://www.netlib.org/lapack/complex/, every single use of the word "transpose" is proceeded by "conjugate". There is also http://www.netlib.org/lapack/Errata/#_strong_span_class_green_bug0024_span_strong_the_notation_a_is_confusing_for_complex_matrices_does_a_stand_for_a_transpose_of_a_hermitian_transpose , which basically says that the only use of a pure transpose is for BLAS compatibility. Doesn't seem to me like we need both.

**Comment by kortschak** [comment]
Good! Decided.
