### ISSUE TITLE
Stack and Augment do not allow identical receiver

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#287]
The code for stack and augment right now has 
````
if ac != bc || m == a || m == b {
	panic(ErrShape)
}
````
In line with the rest of the code, this should not panic if one of the inputs equals the receiver. If it should panic (for whatever reason), it should have a better message than "ErrShape"

**Comment by btracey** [comment]
Ah, of course. It's a non-zero receiver with the wrong size. Is it worth having a different error message? The current one is correct, but it's tempting to think (as I did), that you can do a = [a; b]

**Comment by kortschak** [comment]
The error is the correct one. The problem *is* that the shape is wrong - the way we figure that out is just not by direct comparison of dimension but rather by deduction. I was think that maybe the docs should be improved, but I just looked at them and they are explicit about the size restrictions.

**Comment by kortschak** [comment]
Closing because we already say, "Stack will panic if ... the constructed stacked matrix is not the same shape as the receiver."
