### ISSUE TITLE
Odd determinant of matrix

### ISSUE THREAD

**Issue by ehrt74** [gonum/matrix#291]
m := mat64.NewDense(2,2, []float64{1,0,0,1})
    fmt.Print(mat64.Det(m)) // prints 2

I think calling the floats.LogSumExp method in lu.DetLog is the problem. the logs of the diagonal entries in the LU matrix should be added, not the exps of the logs.

The permutation list should also be used to determine the sign of the determinant, I think.

**Comment by kortschak** [comment]
Using `floats.Sum` does fix this, and yes, the sign calculated currently is wrong, for e.g. `[1 2 0 ; 0 1 2; 0 2 1]`, without a change to the method for that as well.

**Comment by kortschak** [comment]
Note also a documentation error in `(*LU).Pivot` which should be fixed at the same time; `s/If pivot == nil/If swaps == nil/`.

**Comment by btracey** [comment]
I'll fix this shortly. Thanks for the report.

**Comment by ehrt74** [comment]
Thanks!

**Comment by btracey** [comment]
(Shortly = later tonight)

**Comment by btracey** [comment]
Thanks again for the report. Sorry for the error.

**Comment by ehrt74** [comment]
I must say, this is pretty awesome :) I find something I think is an error and you fix it within 3 hours :D
