### ISSUE TITLE
matrix: Interop between mat64 and cmat128

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#308]
Not sure what the right place for this is, so here we are.

I'm looking in to the redesign of Eigen. I don't understand how the API surface is supposed to look so that they can interoperate.

The other factorization methods have methods on the extraction type to get the bounds. LFromLU, for example, is a method on *Dense. For Eigen, we want something like

```
func (c *cmat128.Dense) Eigenvalues(mat64.Eigen){...}
```

However, we can't add methods to cmat128.Dense in mat64, and I think the plan was to not have cmat128 import mat64. We have the conv routines, but I don't see how they solve this problem.

**Comment by kortschak** [comment]
For the Eigen values, it seems to me that the best way is to just use a []complex128. The Eigen vectors are the tricky bit.

**Comment by btracey** [comment]
Yes. Sorry, I meant Eigenvectors

**Comment by btracey** [comment]
This sort of interop should be determined though before stability. B = A^H * A  is a mat64.SymDense; we'll want to pass matrices in both directions.

**Comment by kortschak** [comment]
> This sort of interop should be determined though before stability.

Absolutely. That's why #134 and #283 are in API stability.

**Comment by btracey** [comment]
Understood.

**Comment by kortschak** [comment]
> B = A^H * A is a mat64.SymDense

I don't think that we can do this nor that we should. If we start with A being complex then the result of that operation is complex, though with the imaginary component being zero. It should be up to the user to either know this or test for it and be able to take the cmat128.Matrix result and extract the real part - this is what conv does.

```
type symShim struct {
    Matrix
}

func (s simShim) Symmetric() int {
    r, c := s.Dims()
    if r != c {
        panic(mat64.ErrShape)
    }
    return r
}
```
and then

```
var tmp cmat128.Dense
tmp.Mul(a.H(), a)
n, _ := tmp.Dims()
b := mat64.NewSymDense(n, nil)
b.CopySym(symShim{conv.NewReal(&tmp)})
```

**Comment by btracey** [comment]
The plan is to merge `cmat128` and `mat64`

**Comment by btracey** [comment]
This has been done.
