### ISSUE TITLE
Delete RowColer interface?

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/matrix#328]
Previous discussion from #327 :

> V: Why does the RowColer interface exist?

> B: Historical reasons. Dense used to have these methods. It should have been deleted but was not.

> V: So, can it be deleted now?

> B: I think so. @kortschak should confirm.

> D: The only reason for Dense to have Row or Col is to allow it to interoperate with another RowColer at a performance level greater than you would get if it were just a Matrix. If we don't care about that, those methods can go away.

**Comment by vladimir-ch** [comment]
> D: Also, the existence of RowColer is for that reason - it makes our entry to BLAS at level 2 for each interface method call. This is worse than the level 3 entry we get for a RawMatrixer, but better than calling At O(n^3) times.

> B: Right, but on that argument shouldn't it be individually a Rower and a Coler? Aren't they often used individually in a method?

> D: Combinatorically that is bad. AxB requires that A be a Rower and B be a Coler. Explaining this in the docs in such a way that makes it clear why AxB is faster than BxA where possible is not somewhere I want to go.

**Comment by kortschak** [comment]
Removing RowColer and SetRowColer deletes 202 lines of code in mat64 (excluding test code - ~245 including tests).

**Comment by kortschak** [comment]
Fixed via #329.
