### ISSUE TITLE
mat64: extend aliasing detection to types other than RawMatrixer

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#336]
Currently we perform alias detection for RawMatrixer types. We should cover:

- [x] RawSymmetricer
- [x] RawTriangular
- [x] RawVectorer
- [x] RawMatrixer against RawVectorer (special case).

We have alias detection code in shadow.go, but it needs to be wired in to the user-facing calls.

There is currently no direct way to do comparison for RawMatrixer against Vector, but a small helper to convert a Vector to a blas64.General will suffice.

**Comment by kortschak** [comment]
A question that I don't remember the answer to, though I think it has been discussed. Why are we not checking overlap during Copy calls? I don't see any obvious reason why we don't.

**Comment by btracey** [comment]
Depends on how much we want to match the builtin. The builtin copy is fine with overlap. Copy is the weird function in mat64, so it's not clear it must obey the rules of the other functions.

**Comment by kortschak** [comment]
The builtin is fine with overlap because it has an understanding of direction (see [here](http://play.golang.org/p/J-H6SgvCHA)). We don't, because BLAS doesn't. We could, though then we'd need more unsafe offset support. At the moment it seems to me like it's being special-cased for no real reason except for similarity to copy.

**Comment by kortschak** [comment]
Fixed by #347, #349, #350.
