### ISSUE TITLE
Use in conjunction with gob

### ISSUE THREAD

**Issue by pcostanza** [gonum/matrix#337]
I'm trying to send instances of `mat64.Vector` over a TCP/IP connection, and use `encoding/gob` from the Go standard library for this purpose. While it's possible to make it work, I believe it's currently not ideal.

Encoding (sending) is relatively straightforward:

    func EncodeVector(enc *gob.Encoder, v *mat64.Vector) {
        enc.Encode(v.RawVector().Data)
    }

Encoding the vector instance directly, like in `enc.Encode(v)` is not possible, because the instance variables of the `mat64.Vector` struct are not exported, and therefore the gob library does not (cannot?) access them. Encoding the raw `[]float64` slice instead is fine, though.

However, decoding is wasteful. In my version, it currently looks like this:

    func DecodeVector(dec *gob.Decoder, v *mat64.Vector) *mat64.Vector {
        floats := v.RawVector().Data
        dec.Decode(&floats)
        return mat64.NewVector(len(floats), floats)
    }

While I'm making some attempt to reuse the raw `[]float64` slice of an existing vector, there is actually a good chance a new slice will be created, and on top of that, a new `mat64.Vector` instance needs to be created in any case.

My preference would be to be able to say `dec.Decode(&v.RawVector().Data)`, but Go doesn't allow for taking the address of the field `Data` in the non-addressable instance returned by `RawVector()`, which is probably good, because the original `Data` field inside `v` would not be assigned to if a new slice needs to be allocated.

Do you see a possibility to make `gonum/matrix` interact better with `encoding/gob`? Or am I missing a way to have them work better together already? (I'm new to Go, so please accept my apologies if I'm missing something obvious here.)

Thanks,
Pascal

**Comment by btracey** [comment]
If Vector et al were to implement the GobEncoder and GobDecoder interfaces would that fix the problm?

**Comment by jonlawlor** [comment]
I think it just needs to implement MarshalBinary and UnmarshalBinary - see the EncodeDecode example in the gob library.  The example even uses a vector type with an unexported field!

**Comment by btracey** [comment]
It could also implement MarshalBinary. If you'll notice, however, that example marshals the vector into human-readable numbers for strings. It's not meant to describe how one should always do it. mat64.Dense implements MarshalBinary as a cross-language encoding of the type. Vector can implement MarshalBinary, but that too should be cross-language. The upside to also implementing GobEncoder is that gob is efficient in sending data. If the vector is mostly zeros, for example, then gob will send ~1 byte per element while MarshalBinary will be ~ 8 bytes per element.

**Comment by kortschak** [comment]
The answer here is to make it implement encoding.BinaryMarshaler and encoding.BinaryUnmarshaler. gob encoding can be considered later. The other mat64 types probably also want (un)marshaling behaviour.

**Comment by btracey** [comment]
They aren't necessarily the same though. MarshalBinary just marshals the working range of the matrix. This makes sense as it's intended to be cross platform. Gob is explicitly go specific, and so it may make sense to have gob encode everything, for example capCols in mat64.Dense.

**Comment by kortschak** [comment]
Yes, I understand that they are not the same. I just don't think there is a massive need for the Go-specific case yet - the only difference is the wire efficiency since an encoding.{BinaryMarshaler ,BinaryUnmarshaler} will be correctly handled by gob.{Encode,Decode}. Persisted data may be an issue, so don't do that.

**Comment by sbinet** [comment]
I believe we should do as I originally started in #78.
in the end the PR was restricted to only implement `encoding.Binary{Unm,M}arshaler` for `mat64.Dense` but, in light of this new use case, we should do the same for `mat64.Vector`.

**Comment by pcostanza** [comment]
Thanks a lot for the consideration and discussion. My request above for supporting encoding/gob specifically was due to a lack of understanding the whole picture. It now seems to me that the BinaryMarshaler and BinaryUnmarshaler interfaces would indeed do what I need, so I'd be very happy with that solution.
