### ISSUE TITLE
matrix/mat64: consider whether a row vector type should be added

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#365]
This comes out of discussion in #361. The answer is probably no, but I want to decide formally before API stability.

There is a need to be able to perform a `dst.Copy(vec.T())` where `vec` is a vector shadowing the destination row in `dst` since `vec` represents a column vector, even when it is the result of a `dst.RowView(i)` call.

The problem in #361 is a result of this semantic abuse. A possible solution (proposed here) is to change the signature of `RowView` to `RowView(int) *Row`, `ColView` to `ColView(int) *Col` and derive `Row` and `Col` from `Vector`. `Col` becomes a method limited alias of `Vector` (both `Col` and `Row` must satisfy `Matrix` but needn't have the other methods. This adds a level of complexity since now rows or columns must be converted to a Vector for some operations and some operations will need to have additional type switch cases, but we can remove the exception for unitary stride in `Copy` goes away and the type system is more consistent.

**Comment by vladimir-ch** [comment]
It would bring its own set of implications but `RowView` and `ColView` could return a `*Dense` instead of `*Vector`.

**Comment by kortschak** [comment]
There still needs to be a way of getting a `Vector` from a `Dense`.

**Comment by kortschak** [comment]
Here is a sketch (minimal changes wrt method addition): https://github.com/gonum/matrix/commit/405624d832532177240971f8463cbb2f4db1aa18

**Comment by btracey** [comment]
https://github.com/gonum/gonum/issues/167 is the new issue for this.
