### ISSUE TITLE
The number of interfaces cause many edge cases

### ISSUE THREAD

**Issue by jonlawlor** [gonum/matrix#38]
This is following up on discussion in https://github.com/gonum/stat/pull/19

As currently defined, the interfaces in mat64/ make it so that you might get a Matrix which doesn't implement various matrix operations (such as Col, Row, Add, Mul, ...) which makes implementing functions which accept a Matrix full of edge cases.  A caller has to see if the input Matrix implements arithmetic (for example) and then perhaps have a fallback, and another fallback, and so on.  It makes it difficult to implement and test.

In addition, many of the methods panic when there is no blas engine.  We should probably register goblas by default when it is ready, which will reduce the dimensions of the possible interfaces.

One way to do this is to make methods like Row, Col, Add, Mul, etc. have sigs like
```go
Col(x Matrix, i int) z []float64 { ... }
```
Which would then chose from the available interfaces of x and y to produce a result.  For example, if x implements Vectorer, then it could just call x.Col(i), otherwise, if it implements RawMatrixer, then it could just call RawMatrix() and pull the values out at the appropriate indexes.  If that is not available, then it could call At.

Alternatively, all of the interfaces could be folded into Matrix, so that *all* Matrixes would have to implement Col, and Row, and etc.  That would be easier if goblas was always on.

**Comment by btracey** [comment]
I wonder if the package is too object-oriented at the moment, for reasons that @jonlawlor mentions. It can be hard to perform operations on abstract matrices. In some cases, this is a good idea (the signatures of Add and AddSym are different for a reason), but in other cases, like Col, it doesn't seem to be. 

An alternate proposal would be the following: A specific functionality is a method if, and only if, it does one of the following:
1) Implements a package-level interface (i.e. the methods of Matrix)
2) Modifies the values in the receiver (many of the arithmetic operations)
3) Exposes data that could modify the value of the receiver (RawRowView)
4) Involves data specific to the matrix class.

If the functionality does not fit into one of those categories, it is a package-level function, taking in a Matrix (or a specific matrix class). 

Here's what I see based on the current methods of dense. Number is the category under which it falls, F means will become a function. Specific other cases.
```
Add - 2
Apply - 2
At - 1
Augment - 2
Caps - 4
Clone - 2
Col - F
ColView - 3
Copy - 2
Dims - 1
DivElem - 2
Dot - F
Equals - F
EqualsApprox - F
Exp - 2
Grow - 2
L - Should be a method on Triangular
MarshalBinary - 4 (marshaling in general will be implementation dependent)
Max - F
Min - F
Mul - 2
MulElem - 2
Norm - F
Outer - 2
Pow - 2
RankOne - 2
RawMatrix - 3
RawRowView - 3
Reset() - 2
Row - F
RowView - 2
Scale - 2
Set* - 2
Solve* - 2
Stack - 2
Sub - 2
Sum - F
T - 1
TCopy - 2
Trace - F
U - Should be a method on Triangular
UnmarshalBinary - 4
View - 2
````

**Comment by btracey** [comment]
This proposal would, for example, decide #159 and help to fix #138 .

**Comment by kortschak** [comment]
SGTM

**Comment by btracey** [comment]
Fixed!
