### ISSUE TITLE
matrix/mat64: Should view follow Go slicing syntax

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#405]
Dense.View() asks for a starting point, and a number of rows to extend. It feels like View should take Go slicing syntax; instead specifying {lo, high}

Specifically, rather than `func (m *Dense) View(i, j, r, c int) Matrix`, perhaps it should instead be `func (m *Dense) View(rLo, rHi, cLo, cHi)`.

**Comment by kortschak** [comment]
How often do we take the result of a Dims call and use that in r and c and how often do we view from one element coordinate to another?

If we do make this change I would want it to go through a three step process. 1. Create a Slice method with the new semantics above, 2. replace the calls to View with calls to Slice, and 3. rename Slice to view.

This is to avoid errors during the change - the types are the same so this is real risk.

**Comment by sbinet** [comment]
we should provide an `eg` script to migrate in one go.
see, for example:
 https://github.com/sbinet/envol-2016-go/blob/master/api/api_eg.go

that would probably read, for this api migration:

```go
// +build ignore

// package P is a placeholder to run eg, like so:
//  $> eg -t ./api_eg.go -w -transitive my/pkg/p1 my/pkg/p2
package P

import (
	"github.com/gonum/matrix/mat64"
)

func before(m *mat64.Dense, i, j, r, c int) mat64.Matrix { return m.View(i, j, r, c) }
func after(m *mat64.Dense, i, j, r, c int) mat64.Matrix  { return m.Slice(i, i+r, j, j+c) }
```

**Comment by kortschak** [comment]
This has been done in gonum/gonum.
