### ISSUE TITLE
Failed io_tests

### ISSUE THREAD

**Issue by jackfrye** [gonum/matrix#430]
Go version: go version go1.7.4 windows/amd64
Running on go test io_tests.go.

Output:
# command-line-arguments
.\io_test.go:19: undefined: Dense
.\io_test.go:20: undefined: Dense
.\io_test.go:21: undefined: Vector
.\io_test.go:22: undefined: Vector
.\io_test.go:27: undefined: Dense
.\io_test.go:28: undefined: Matrix
.\io_test.go:98: undefined: sizeFloat64
.\io_test.go:98: undefined: sizeInt64
.\io_test.go:293: undefined: Vector
.\io_test.go:294: undefined: Matrix
.\io_test.go:98: too many errors
FAIL    command-line-arguments [build failed]

**Comment by kortschak** [comment]
Can you post the output of `git rev-parse HEAD` when you are in `$GOAPTH/src/github.com/gonum/matrix` and what command you used to invoke the tests. This failure should not be possible; none of the labels in the errors above are protected by build tags and `io_test.go` is in "github.com/gonum/matrix/mat64", so they should all be visible.

**Comment by jackfrye** [comment]
I may be running the wrong command to test.

C:\Users\jackf_000\Developer\Go\src\github.com\gonum\matrix\mat64>git rev-parse HEAD
96a2f64ca6c006823bbfe5f92981534fd0a991b9

C:\Users\jackf_000\Developer\Go\src\github.com\gonum\matrix\mat64>go test io_test.go
# command-line-arguments
.\io_test.go:19: undefined: Dense
.\io_test.go:20: undefined: Dense
.\io_test.go:21: undefined: Vector
.\io_test.go:22: undefined: Vector
.\io_test.go:27: undefined: Dense
.\io_test.go:28: undefined: Matrix
.\io_test.go:98: undefined: sizeFloat64
.\io_test.go:98: undefined: sizeInt64
.\io_test.go:293: undefined: Vector
.\io_test.go:294: undefined: Matrix
.\io_test.go:98: too many errors
FAIL    command-line-arguments [build failed]

**Comment by kortschak** [comment]
Try `go test github.com/gonum/matrix/mat64 -run (Marshal|Unmarshal|IO)` (leave off the `-run (Marshal|Unmarshal|IO)` to run all the tests in the package). What you have done is try to run the tests with only that file, which obviously lacks the entirety of the rest of the package. Probably you should read the output of `go test -help`.

**Comment by jackfrye** [comment]
C:\Users\jackf_000\Developer\Go\src\github.com\gonum\matrix\mat64>go test
PASS
ok      github.com/gonum/matrix/mat64   5.795s

Got you. Thanks. Still pretty new to Go. Appreciate the guidance.

**Comment by kortschak** [comment]
No worries. Closing this.
