### ISSUE TITLE
matrix/mat64: Question: add `mat64.Merge` helper function

### ISSUE THREAD

**Issue by ChristopherRabotin** [gonum/matrix#431]
I propose to add a function called `mat64.Merge(r, c int, a, b mat64.Matrix)` which creates a new matrix of the same type as those provided (type will be checked) but of size (r,c).

For example, I am encountering a situation where I am building a 6x3 matrix which is made up of two previous computed 3x3 matrices. I would then call this function as `C := mat64.Merge(6, 3, A, B)`.

I understand that, as a helper function, it may not be appropriate to place it in `matrix/mat64`, but I'm asking nevertheless.

**Comment by btracey** [comment]
We have 
https://godoc.org/github.com/gonum/matrix/mat64#Dense.Stack <https://godoc.org/github.com/gonum/matrix/mat64#Dense.Stack>
and
https://godoc.org/github.com/gonum/matrix/mat64#Dense.Augment <https://godoc.org/github.com/gonum/matrix/mat64#Dense.Augment>

which sounds like it meets your needs.

**Comment by ChristopherRabotin** [comment]
Great! Sorry, I didn't see those before.
