### ISSUE TITLE
mat64: rethink XFromY API for extracting matrices from decompositions

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#435]
When there were few of these it made sense to have the extractions be a method on `*Dense` or other matrix types. However, now (partly due to me) there is a proliferation of these on `*Dense`. Having just had a look at `stat.CC` I'm not averse to the approach that is used there with `Left` and `Right`. We should consider migrating to this approach (at least for some/most? of the decompositions).

This change would have the advantage of keeping the documentation around the decompositions together for each type of decomposition, would reduce the number of methods on `*Dense` and would avoid giving the impression that there are blessed decompositions (that packages outside mat64 cannot match).

**Comment by btracey** [comment]
SGTM

**Comment by kortschak** [comment]
This has been done in gonum/gonum
