### ISSUE TITLE
Add discussion of using matrices and views

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#50]
It is probably worth adding a discussion on how to be a good citizen when it comes to manipulating matrix data directly. As far as we're concerned, it's definitely discouraged to get the underyling matrix directly, but we allow it for a number of good reasons. Developers of (especially low level) packages that take a Dense are likely to do so as well. We should talk about the correct way to do so, for example by showing the correct way to add all of the elements of a matrix is by looping over the rows and not by doing floats.Sum on the data slice itself.

**Comment by btracey** [comment]
Do we think this issue is solved now that we have blas64, or do we still want more documentation? mat64 is in a much better state than it was, and these days I only access the raw data with RawRowView.

**Comment by kortschak** [comment]
I think we are good now. Unless you want to get really low level (in which case you either know what you are doing or deserve the ensuing problems) blas64 holds your hand nicely.
