### ISSUE TITLE
Should we use goblas instead of cblas for tests?

### ISSUE THREAD

**Issue by jonlawlor** [gonum/matrix#62]
Currently, running tests on the `matrix\mat64` package requires an installed cblas library.  Now that @btracey has completed a pure go blas implementation in `blas\goblas`, we may want to change the tests to use goblas, so that users will be able to run go test without installing cblas.

This would be particularly useful for travis-ci, which currently takes ~10m to run, almost all of which is spent making OpenBLAS, which could be reduced to something like a minute.  There is also an intermittent error that occurs during travis builds, which happens when it fails to download the netlib cblas header.

All of the blas libraries *should* produce the same output (ha, ha), and if they don't then the appropriate place to test is probably in the `blas` package instead of here.  Benchmarks may still be interesting though.

**Comment by kortschak** [comment]
SGTM

The various gonum/blas implementations need to be tested against each other, but that should happen in that package.

At some stage the blas implementation registration will happen in gonum/blas/something, but in the mean time, changing the declaration to goblas and dropping the the init registration in the testing code, and then dropping the OpenBLAS rigmarole should be enough. For extra credit, move the init registration into a cblas.go file with `//+build cblas`.
