### ISSUE TITLE
Change signature of Vec.Mul

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#80]
It's not true that a Vec can result from multiplying two general matrices. A vec can only result from multiplying a Vector with a matrix. I vote we reflect this in the signature, and instead make it

func (v *Vector) Mul(a Matrix, trans bool, b *Vec)

This signature maps very nicely to D*mv calls.

**Comment by kortschak** [comment]
This clobbers the possibility of *Vector satisfying Muler.

**Comment by btracey** [comment]
Which is fine, because it's not a Muler. A Vector results from multiplying a Matrix and a Vector, not from multiplying a Matrix with a Matrix.

**Comment by kortschak** [comment]
True.

**Comment by kortschak** [comment]
However, we can currently do so when the dims are correct. I'd prefer to keep that and add, say MulVec.

**Comment by btracey** [comment]
Why though? Most code that uses Vec as a generic Muler will panic, because the intended use of a Muler is as a receiver for multiplying two matrices, and generic matrix multiplication this is wrong. In addition, this does not play well with the other matrix types. Symmetric does not really implement Muler either, as the multiplication of two Matrix is not symmetric. Instead, it implements "SymMuler", where A and B are both symmetric matrices. If Vec improperly implements Muler, then presumably Symmetric should also. The first step of Symmetric will be to check that the Matrix is actually a SymMatrix, at which point all that you've done is lose type safety. The same thing is true for Triangular matrices and Banded matrices. All of them support some form of multiplication, but none of them truly implement Muler except Dense. I don't see what satisfying the same interfaces as Dense gives you except for a false sense of consistency and interoperability.

**Comment by kortschak** [comment]
Mainly I want to differentiate it from Mul.

**Comment by btracey** [comment]
Maybe I'm being too strong, but what I see is a loss of guaranteed
correctness,  and I don't see algorithms that would benefit from the extra
generality even though the generic inputs are wrong. The inputs are as
general as they can be for the various types (all of the types implement
Matrix), it's the receivers that are picky because they have to be to
maintain consistency. It seems that we should enforce as much as possible
at compile time. Are there cases you have in mind where you want vec as a
muler?

**Comment by kortschak** [comment]
I should be been more clear in the last comment, sorry. I mean drop Mul from Vec by renaming it to e.g. MulVec. This is purely to avoid doc reader confusion.

**Comment by btracey** [comment]
Yes,  understood.  SGTM

**Comment by btracey** [comment]
This has been fixed.
