### ISSUE TITLE
Problems when a Dense/Vector is a receiver and an argument

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#93]
See discussion in #92 

At the moment, this is a problem throughout Dense and in Vector. 

When it is the same, new memory is allocated to avoid shadowing. This new data is used in place of the old matrix. There are two problems with the current approach
1) (Relatively easy): In the code, there is no check that the receiver is the correct size. For example, if we have a.Mul(a, b), a is successfully overwritten even if b is not an nxn matrix. This is contrary to the current policy that sizes are only fungible when the matrix is zero.
2) (Harder). This behavior also does not behave well with views. Instead of the new allocated memory replacing of the old data, in cases where a is a subset of a different matrix, the new data should be copied into the old locations.

**Comment by kortschak** [comment]
If we keep a pointer (perhaps weakened to a uintptr - though this requires that we import unsafe) to the origin of a view when we create it, we can know if a Dense is a view and what it is a view of.

**Comment by kortschak** [comment]
@btracey I believe your recent changes cleaning up the prologue code have fixed this. Do you think this is true?

**Comment by btracey** [comment]
Yes, although I don't know that it's been enacted everywhere.
